- name: cCeate flask directory 
  file:
    path: "{{ image_directory }}/backend"
    recurse: yes
    state: directory

- name: Copy flask dockerfile
  copy: 
    src: ./images/backend/Dockerfile
    dest: "{{ image_directory }}/backend/Dockerfile"

- name: Copy flaskProject
  copy:
    src: flaskProject 
    dest: "{{ image_directory }}/backend/"

- name: Build flask image
  docker_image: 
    name: backend
    tag: latest 
    source: build 
    build:
      path: "{{ image_directory }}/backend"
      pull: false 
    state: present

- name: Run a flask container
  docker_container:
    image: backend:latest 
    name: flask
    state: started 
    ports: 
      - 8081:8081
      - 5000:5000