---
- name: Create mount directory
  file: 
    path: "{{ mount.path }}"
    state: directory
- name: Mount volume 
  mount:
    path: "{{ mount.path }}"
    src: "{{ mount.src }}"
    fstype: ext4
    state: mounted
    boot: true