---
- name: ensure mount binding directory exists 
  file: 
    path: "{{ bind_mount_path.src }}"
    recurse: yes
    state: directory

- name: copy docker.ini file to server
  copy:
    src: ./docker.ini
    dest: "{{ bind_mount_path.src }}/docker.ini"

- name: ensure couchdb image created
  docker_container:
    image: couchdb:latest
    name: "couchdb"
    volumes: "{{ bind_mount_path.src }}:{{ bind_mount_path.dst }}"

    ports: 
      - "{{ couchdb_port }}:{{ couchdb_port }}"
      - "{{ cluster_comm_port_range_min }}:{{ cluster_comm_port_range_min }}"
      - "{{ cluster_port }}:{{ cluster_port }}" 
    env:
      ERL_FLAGS: '-setcookie "a192aeb9904e6590849337933b000c99" -name "couchdb@{{ inventory_hostname }}'
    state: started

- name: pause set up for 30 seconds
  pause: 
    seconds: 30

- name: set up default databases
  uri:
    url: "http://{{ inventory_hostname }}:{{ couchdb_port }}/{{ item }}"
    user: "{{ user.username }}"
    password: "{{ user.password }}"
    force_basic_auth: yes 
    method: PUT 

    status_code: 
      - 201
      - 412
  with_items: "{{ default_databases }}"
