---
- name: install python docker module
  pip: 
    name: docker 
    state: present
    
- name: Init a new swarm
  docker_swarm:
    state: present
    force: yes
    advertise_addr: "{{ ansible_host }}"
  register: result
  when: inventory_hostname == groups['config'][0]

- name: Get join-token for manager nodes
  set_fact:
    join_token_manager: "{{ hostvars[groups['config'][0]].result.swarm_facts.JoinTokens.Manager }}"

- name: Get join-token for worker nodes
  set_fact:
    join_token_worker: "{{ hostvars[groups['config'][0]].result.swarm_facts.JoinTokens.Worker }}"

- name: Join other managers
  docker_swarm:
    state: join
    join_token: "{{ join_token_manager }}"
    advertise_addr: "{{ ansible_host }}"
    remote_addrs: "{{ groups['config'][0] }}"
  when:
    - inventory_hostname in groups['config']

- name: Join workers
  docker_swarm:
    state: join
    join_token: "{{ join_token_worker }}"
    advertise_addr: "{{ ansible_host }}"
    remote_addrs: "{{ groups['config'][0] }}"
  when:
    - inventory_hostname not in groups['config']
