version: '3'

services:
  backend:
    build: backend
    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - ./backend:/flaskProject
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - "5000:5000"

  balancer:
    build: balancer
    volumes:
      - ./balancer:/etc/nginx/conf.d
    ports: 
      - 8081:8081

  frontend:
    build: frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/material-kit-react
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - backend
  