---
- name: Install pip
  ansible.builtin.apt:
    name: ["python3-dev", "python3-setuptools", "python3-pip"]
    state: latest
    update_cache: yes

- name: Update pip
  ansible.builtin.pip:
    name: pip
    state: latest