---
- name: Build Docker image and run image in container
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Build Docker image
      docker_image:
        name: mastodon-client
        path: dockerfile
        buildargs:
          - PYTHON_SCRIPT_PATH=mastodon-couchdb.py

    - name: Run Docker container
      docker_container:
        name: mastodon-container
        image: mastodon-client
        state: started
