version: '3'
services:
  app:
    image: mastodon-client:mastodon-client
    deploy:
      replicas: 3
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.ip==<ip1>
          - node.labels.ip==<ip2>
          - node.labels.ip==<ip3>
    ports:
      - 8080:80
    environment:
      - ENV_VAR_NAME=value
