---
- name: ensure mount binding directory exists 
  file: 
    path: "{{ bind_mount_path.src }}"
    recurse: yes
    state: directory

- name: copy default.conf file to server
  copy:
    src: ./default.conf
    dest: "{{ bind_mount_path.src }}/default.conf"

- name: ensure nginx image started
  docker_container:
    image: nginx:latest
    name: "nginx"
    volumes: "{{ bind_mount_path.src }}:{{ bind_mount_path.dst }}"
    ports: 
      - "{{ nginx_port }}:{{ nginx_port }}"
    state: started