- name: create twitter_processor directory 
  file:
    path: "{{ image_directory }}/twitter_processor"
    recurse: yes
    state: directory

- name: copy twitter_processor file to server
  copy:
    src: ./{{ item }}
    dest: "{{ image_directory }}/twitter_processor/{{ item }}"
  with_items:
    - downsizing_couch.py
    - au.json
    - twitter-huge.json.zip

- name: copy flask dockerfile
  copy: 
    src: ./images/twitter_processor/Dockerfile
    dest: "{{ image_directory }}/twitter_processor/Dockerfile"

- name: build twitter_processor image
  docker_image: 
    name: backend
    tag: latest 
    source: build 
    build:
      path: "{{ image_directory }}/twitter_processor"
      pull: false 
    state: present

- name: run a twitter_processor container
  docker_container:
    image: backend:twitter_processor
    name: twitter
    state: started 
    auto_remove: yes
    cpus: 2
    ports: 
      - 8081:8081