- name: create twitter_processor directory 
  file:
    path: "{{ image_directory }}/twitter_processor"
    recurse: yes
    state: directory

- name: copy twitter_processor file to server
  copy:
    src: ./{{ item }}
    dest: "{{ image_directory }}/twitter_processor/{{ item }}"
  with_items:
    - downsizing_couch.py
    - au.json
