---
- name: Set up modules for all instances
  hosts: multi
  vars_files:
    - variables/mrc.yaml
    - variables/docker.yaml
  gather_facts: yes
  become: yes
  roles:
    - role: common
    - role: public_keys
    - role: docker

- name: Set up modules for app server
  hosts: app
  vars_files:
    - variables/mrc.yaml
  become: yes
  roles:
    - role: nodeJS
    - role: react

- name: Set up couchdb 
  become: yes
  hosts: db 
  vars_files:
    - variables/couchdb.yaml
  roles:
    - couchdb 

- name: Set up cluster
  become: yes
  hosts: worker 
  vars_files:
    - variables/couchdb.yaml
  roles:
    - cluster

