---
- name: Set up modules for all instances
  hosts: multi
  vars_files:
    - variables/mrc.yaml
    - variables/docker.yaml
  gather_facts: yes
  become: yes
  roles:
    - role: public_keys
    - role: chrony
    - role: volume
    - role: common
    - role: public_keys
    - role: docker

- name: Set up couchdb 
  become: yes
  hosts: db 
  vars_files:
    - variables/couchdb.yaml
  roles:
    - couchdb 

- name: Set up cluster
  become: yes
  hosts: sender
  vars_files:
    - variables/couchdb.yaml
  roles:
    - cluster

- name: Set up load balancer
  become: yes
  hosts: app 
  vars_files:
    - variables/nginx.yaml
  roles:
    - nginx

# - name: Set up databases
#   hosts: app 
#   become: yes
#   vars_files:
#     - variables/couchdb.yaml
#     - variables/mrc.yaml
#   roles:
#     - database
#     - permission
#     - twitter_processor

- name: set up docker swarm 
  hosts: all 
  become: yes 
  roles: 
    - swarm