# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # General Vagrant VM configuration.
  config.vm.box = "ubuntu/jammy64"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider :virtualbox do |v|
    v.memory = 512
    v.linked_clone = true
  end
  # Database server 1.
  config.vm.define "db1" do |db|
    db.vm.hostname = "orc-db1.test"
    db.vm.network :private_network, ip: "192.168.60.4"
  end
  # Database server 2.
  config.vm.define "db2" do |db|
    db.vm.hostname = "orc-db2.test"
    db.vm.network :private_network, ip: "192.168.60.5"
  end
  # Database server 3.
  config.vm.define "db3" do |db|
    db.vm.hostname = "orc-db3.test"
    db.vm.network :private_network, ip: "192.168.60.6"
  end
  # App server.
  config.vm.define "app" do |app|
    app.vm.hostname = "orc-app.test"
    app.vm.network :private_network, ip: "192.168.60.7"
  end  
end
