---
# Install dependencies on the host
- name: Install pip
  become: true
  apt:
    name: ["python3-dev", "python3-setuptools", "python3-pip"]
    state: latest
    update_cache: true

- name: Update pip
  pip:
    name: ["pip", "openstacksdk"]
    state: latest
# pip install --upgrade pip && pip install openstacksdk