---
- name: Copy mastodon files
  copy:
    src: mastodon
    dest: "{{ mastodon_path }}"

- name: Build single Mastodon client Docker image
  docker_image:
    name: mastodon-client
    tag: latest 
    source: build 
    build:
      path: "{{ mastodon_single_path }}"
      pull: false 
    state: present

- name: Run Docker container
  docker_container:
    name: mastodon
    image: mastodon-client
    state: started